package kr.ex.gamearchive.model;

public enum Category {
    ACTION, RPG, SPORTS, STRATEGY, SHOOTING, RACING, SIMULATION, PUZZLE, ADVENTURE, FIGHTING, MUSIC, BOARD, CASUAL, ARCADE, EDUCATION, TRIVIA, CARD, WORD, CASINO, ROLEPLAYING, SOCIAL, MULTIPLAYER, OTHER
}
